### ISSUE TITLE
Response of inventory equipment components "radio" and "modem" provide identical values regardless of their EquipmentCategory

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/AutomatedLinkAcceptanceProxy#167]

**Comment by openBackhaul** [comment]
Might be no error in the applications, but specific to the mediator implementation.
Potentially, problem to be raised in the modelling calls.

**Comment by anacabbar** [comment]
This bug is occuring for correct mediator implementations. Example:

**Obtained response:** 

![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/116157436/05a62056-5884-4686-973a-aff365d44d16)

**Expected response:**

![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/116157436/96efbbf8-c1a4-4c3d-9c66-54eb3f13a090)

**Comment by anacabbar** [comment]
Hi @IswaryaaS , @PrathibaJee ,
Could you please take a look at this? The affected callback is "ReadingTheRadioComponentIdentifiers", and this can be currently reproduced for any split-mount E/// device (MLTN or ML66xx).
Thank you very much! Best regards,
Ana

**Comment by PrathibaJee** [comment]
Hi Ana,
We are looking into it and share you the details as soon as possible.
Many thanks.

Thanks,
Prathiba J

**Comment by PrathibaJee** [comment]
As of now this issue is not reproducible because of a problem( [MicroWaveDeviceInventory/issues/853](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/853)  in the latest tag of the MWDI with the url /core-model-1-4:network-control-domain=cache/control-construct=/equipment=/actual-equipment. So , requested operations to revert the new tag. Once this is done , we shall able to further look into the problem mentioned in this issue.

**Comment by PrathibaJee** [comment]
After reverting the MWDI to the pervious tag , we are able to reproduce this issue in ALAP. We confirm that this is a problem in ALAP that needs to be fixed.
